name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro Passo
        run: date
  job2:
    name: Segundo Job
    runs-on: windows-latest
    steps:
      - name: Segundo Passo
        run: date
  job3:
    name: Terceiro Job
    runs-on: macos-latest
    steps:
      - name: Terceiro Passo
        run: date

  job4:
    name: Ultimo Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Último Passo
        run: date
